#ifndef GUARD_SMCPCORE_BEDROCK_BACKYARD_CONFIG_DETAILS_PLATEFORM_LINUX_H
#define GUARD_SMCPCORE_BEDROCK_BACKYARD_CONFIG_DETAILS_PLATEFORM_LINUX_H
#pragma once

#define SMCP_PLATFORM_NAME_LINUX "Linux"
#define SMCP_PLATFORM_NAME SMCP_PLATFORM_NAME_LINUX

#define SMCP_PLATFORM_LINUX 1

#endif // GUARD_SMCPCORE_BEDROCK_BACKYARD_CONFIG_DETAILS_PLATEFORM_LINUX_H
