#ifndef GUARD_SMCPCORE_BEDROCK_BACKYARD_CONFIG_DETAILS_PLATEFORM_MACOSX_H
#define GUARD_SMCPCORE_BEDROCK_BACKYARD_CONFIG_DETAILS_PLATEFORM_MACOSX_H
#pragma once

#define SMCP_PLATFORM_NAME_MACOSX "Apple Mac OSX"
#define SMCP_PLATFORM_NAME SMCP_PLATFORM_NAME_MACOSX

#pragma message(SMCP_PLATFORM_NAME)

#define SMCP_PLATFORM_MACOSX 1

#endif // GUARD_SMCPCORE_BEDROCK_BACKYARD_CONFIG_DETAILS_PLATEFORM_MACOSX_H